### ISSUE TITLE
Jasper Reports are not Compatible with Latest jfreechart.jar

### ISSUE THREAD

**Issue by bhansali-mukesh** [Jaspersoft/jaspersoft.github.io#1]
Hello Team,
We are using jfreechart.jar version 1.5.0 in our application but Jasper Reports are not compatible with it.

Jasper Reports are compatible with  jfreechart.jar version 1.0.19 and dependent on jcommon.jar version 1.0.23 for some APIs like Method : setPosition ( RectangleEdge r ) etc.

Please update and let me know if we can use latest jfreechart.jar for Jasper Reports as well.

**Comment by maxrabbi** [comment]
Hi this is not the correct place where to open bug fix/enhancement requests.
Please refer to the Community website, and in particular to the JasperReports project tracker.

The link is the following one: https://community.jaspersoft.com/bug-tracker?field_bug_project_target_id=202

**Comment by bhansali-mukesh** [comment]
Thanks for Guidance.
I reported it in bug tracker.
